# Usa la imagen base oficial de Python
FROM python:3.9-slim

# Instala las dependencias necesarias
RUN pip install --no-cache-dir grpcio grpcio-tools pymongo

# Copia el código del servidor al contenedor
WORKDIR /app
COPY . .

# Expone el puerto del servidor gRPC
EXPOSE 50052

# Comando para ejecutar el servidor
CMD ["python", "app.py"]
