# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"P\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x11\n\tcreatedAt\x18\x05 \x01(\t\"N\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\">\n\x10RegisterResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\" \n\x0fGetUsersRequest\x12\r\n\x05token\x18\x01 \x01(\t\".\n\x10GetUsersResponse\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.users.User\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x13GetUserByIdResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\".\n\x11UpdateUserRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"/\n\x12UpdateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\" \n\x12\x44\x65leteUserResponse\x12\n\n\x02id\x18\x01 \x01(\t2\x81\x03\n\x05Users\x12;\n\x08Register\x12\x16.users.RegisterRequest\x1a\x17.users.RegisterResponse\x12\x32\n\x05Login\x12\x13.users.LoginRequest\x1a\x14.users.LoginResponse\x12;\n\x08GetUsers\x12\x16.users.GetUsersRequest\x1a\x17.users.GetUsersResponse\x12\x44\n\x0bGetUserById\x12\x19.users.GetUserByIdRequest\x1a\x1a.users.GetUserByIdResponse\x12\x41\n\nUpdateUser\x12\x18.users.UpdateUserRequest\x1a\x19.users.UpdateUserResponse\x12\x41\n\nDeleteUser\x12\x18.users.DeleteUserRequest\x1a\x19.users.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=22
  _globals['_USER']._serialized_end=102
  _globals['_REGISTERREQUEST']._serialized_start=104
  _globals['_REGISTERREQUEST']._serialized_end=182
  _globals['_REGISTERRESPONSE']._serialized_start=184
  _globals['_REGISTERRESPONSE']._serialized_end=246
  _globals['_LOGINREQUEST']._serialized_start=248
  _globals['_LOGINREQUEST']._serialized_end=295
  _globals['_LOGINRESPONSE']._serialized_start=297
  _globals['_LOGINRESPONSE']._serialized_end=327
  _globals['_GETUSERSREQUEST']._serialized_start=329
  _globals['_GETUSERSREQUEST']._serialized_end=361
  _globals['_GETUSERSRESPONSE']._serialized_start=363
  _globals['_GETUSERSRESPONSE']._serialized_end=409
  _globals['_GETUSERBYIDREQUEST']._serialized_start=411
  _globals['_GETUSERBYIDREQUEST']._serialized_end=443
  _globals['_GETUSERBYIDRESPONSE']._serialized_start=445
  _globals['_GETUSERBYIDRESPONSE']._serialized_end=493
  _globals['_UPDATEUSERREQUEST']._serialized_start=495
  _globals['_UPDATEUSERREQUEST']._serialized_end=541
  _globals['_UPDATEUSERRESPONSE']._serialized_start=543
  _globals['_UPDATEUSERRESPONSE']._serialized_end=590
  _globals['_DELETEUSERREQUEST']._serialized_start=592
  _globals['_DELETEUSERREQUEST']._serialized_end=623
  _globals['_DELETEUSERRESPONSE']._serialized_start=625
  _globals['_DELETEUSERRESPONSE']._serialized_end=657
  _globals['_USERS']._serialized_start=660
  _globals['_USERS']._serialized_end=1045
# @@protoc_insertion_point(module_scope)
