# Usa la imagen base oficial de Python
FROM python:3.9-slim

# Copia el archivo requirements.txt al contenedor
COPY requirements.txt /app/

# Instala las dependencias necesarias
RUN pip install --no-cache-dir -r /app/requirements.txt

RUN pip install grpcio-tools --no-cache-dir
# Copia el código del servidor al contenedor
WORKDIR /app
COPY . .

# Expone el puerto del servidor gRPC
EXPOSE 50051

# Comando para ejecutar el servidor
CMD ["python", "app.py"]
